.PHONY: clean All

All:
	@echo "----------Building project:[ snake - Debug ]----------"
	@cd "snake" && "$(MAKE)" -f  "snake.mk"
clean:
	@echo "----------Cleaning project:[ snake - Debug ]----------"
	@cd "snake" && "$(MAKE)" -f  "snake.mk" clean
